### ISSUE TITLE
损失函数问题

### ISSUE THREAD

**Issue by henuJackSon** [fitzpchao/DTCDSCN#10]
作者，您好，我做二分类变化检测时将我代码的损失函数换成CDLoss，目前损失函数范围是25-26之间。在训练过程中损失函数降低之后再升上去，反反复复震荡。我之前的损失函数使用的是交叉熵损失函数，在训练过程中呈现下降趋势，范围值是0-1之间，请问您训练的时候有保存损失函数的变化图吗？损失函数的变化是怎么样的。
感谢您的回复

**Comment by fitzpchao** [comment]
实在抱歉，这个工作过去时间太长了，已经记不清这些细节了。
