### ISSUE TITLE
改正作者论文中的图错误

### ISSUE THREAD

**Issue by blair2020** [fitzpchao/DTCDSCN#6]
![image](https://user-images.githubusercontent.com/69249732/97257737-bdc2a600-1851-11eb-8405-a6d2b187548b.png)
看了程序后，发现真实的网络结构图如上。作者的原图很有误导性，原图（b）（d）只看后部分，前部分的具体输入和图片不一致。

**Comment by aishiliu** [comment]
请问你是在哪里看到作者的论文和原图的呀

**Comment by aishiliu** [comment]
> ![image](https://user-images.githubusercontent.com/69249732/97257737-bdc2a600-1851-11eb-8405-a6d2b187548b.png)
> 看了程序后，发现真实的网络结构图如上。作者的原图很有误导性，原图（b）（d）只看后部分，前部分的具体输入和图片不一致。

请问你是在哪里看到作者的论文和原图的呀

**Comment by fitzpchao** [comment]
Thank you for discovering this problem! This is to facilitate the division of code modules caused by drawing pictures and the division of functional modules described in the paper is not completely consistent.
