### ISSUE TITLE
关于损失函数的问题

### ISSUE THREAD

**Issue by blair2020** [fitzpchao/DTCDSCN#7]
作者自己设计了一个损失函数，但论文里并未说清楚为什么这么设计损失函数
我看了一下，CDL 大概等于 facal loss + ce loss，然后y = 1 时伽马 =1.5 ；y = 0 时伽马 =1
问题一：facal loss的论文里说伽马 =2最优，作者基于什么理由改为1.5和1？
问题二：facal loss里还有一个关于样本权重的参数阿尔法=0.25，作者为什么抛弃了？

关于facal loss我看的是
https://www.cnblogs.com/king-lps/p/9497836.html

**Comment by fitzpchao** [comment]
Because the two parameters have not been adjusted well, a function of exponential parameters is proposed.
Q1：Sorry! The uploaded version should not be the most accurate version, and I haven't checked the hyperparameters.
Q2：For the convenience of tuning

**Comment by geoyee** [comment]
请问。关于网络的输出，请问这个数据集的标签是需要三个吗？即变化的标签，和两张分割的标签。或者说至少需要两个时段的分割的标签

**Comment by fitzpchao** [comment]
是的，这个地方具有比较大的局限性

**Comment by fitzpchao** [comment]
> 请问。关于网络的输出，请问这个数据集的标签是需要三个吗？即变化的标签，和两张分割的标签。或者说至少需要两个时段的分割的标签

是的，这个地方具有较大的局限性

**Comment by geoyee** [comment]
> > 请问。关于网络的输出，请问这个数据集的标签是需要三个吗？即变化的标签，和两张分割的标签。或者说至少需要两个时段的分割的标签
> 
> 是的，这个地方具有较大的局限性

好的了解了，感谢回复

**Comment by fitzpchao** [comment]
> > > 请问。关于网络的输出，请问这个数据集的标签是需要三个吗？即变化的标签，和两张分割的标签。或者说至少需要两个时段的分割的标签
> > 
> > 
> > 是的，这个地方具有较大的局限性
> 
> 好的了解了，感谢回复

我们之前的经验发现，我们将建筑物分割和变化检测两类数据集共享部分特征提取层，同时训练也是对变化检测有提高的，但是对于分割任务的精度是有损害的。

**Comment by geoyee** [comment]
> > > > 请问。关于网络的输出，请问这个数据集的标签是需要三个吗？即变化的标签，和两张分割的标签。或者说至少需要两个时段的分割的标签
> > > 
> > > 
> > > 是的，这个地方具有较大的局限性
> > 
> > 
> > 好的了解了，感谢回复
> 
> 我们之前的经验发现，我们将建筑物分割和变化检测两类数据集共享部分特征提取层，同时训练也是对变化检测有提高的，但是对于分割任务的精度是有损害的。

了解，感谢您的无私分享，这将是有帮助的。
